version: '3.9'
services:
  aut_landing_web: 
    container_name: aut_landing_web
    image: aut_landing_web
    build: ./

  aut_landing_nginx:
    container_name: aut_landing_nginx
    image: aut_landing_nginx
    build: ./nginx
    ports:
      - 3001:9080

networks:
  aut_landing: